### ISSUE TITLE
"Module file was created by an older version of the compiler"

### ISSUE THREAD

**Issue by delebedev** [brow/Sukhasana#1]
Latest Xcode Beta (Version 6.3 (6D520o)):
I've done the following:
`$ carthage botstrap
$ carthage build`
Then I've tried to build the project and got:
`/Users/lebedzeu/src/git/Sukhasana/Sukhasana/Other/SignalOperators.swift:9:8: Module file was created by an older version of the compiler: /Users/lebedzeu/src/git/Sukhasana/Carthage/Build/Mac/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/x86_64.swiftmodule`

**Comment by brow** [comment]
Thanks for pointing this out, @garnett. You would need to use `xcode-select` to get Carthage to build the dependencies with Xcode 6.3. But that won't work because neither ReactiveCocoa nor Alamofire supports Swift 1.2 yet.

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/1775
https://github.com/Alamofire/Alamofire/pull/338

 I'll get this project working with Xcode 6.3 once it comes out of beta.
